language: node_js

node_js:
  - node

branches:
  - master
  - /^greenkeeper/.*$/

before_script:
  - npm install

script:
  - node app.js &
  - npm test

notifications:
  email:
    on_failure: change
    on_success: change
